export const INVITE_CODE_LENGTH = 6;
export const INVITE_CODE_MAX_USES = 50;
export const INVITE_CREDITS_INVITER = 3;
export const INVITE_CREDITS_INVITEE = 3;
export const INVITE_GUARD_WINDOW_MS = 24 * 60 * 60 * 1000;

export const INVITE_CODE_CHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
